In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

In [2]:
from sklearn.datasets import load_breast_cancer

In [3]:
x,y = load_breast_cancer(return_X_y = True)

In [4]:
print(x.shape)
x

(569, 30)


array([[1.799e+01, 1.038e+01, 1.228e+02, ..., 2.654e-01, 4.601e-01,
        1.189e-01],
       [2.057e+01, 1.777e+01, 1.329e+02, ..., 1.860e-01, 2.750e-01,
        8.902e-02],
       [1.969e+01, 2.125e+01, 1.300e+02, ..., 2.430e-01, 3.613e-01,
        8.758e-02],
       ...,
       [1.660e+01, 2.808e+01, 1.083e+02, ..., 1.418e-01, 2.218e-01,
        7.820e-02],
       [2.060e+01, 2.933e+01, 1.401e+02, ..., 2.650e-01, 4.087e-01,
        1.240e-01],
       [7.760e+00, 2.454e+01, 4.792e+01, ..., 0.000e+00, 2.871e-01,
        7.039e-02]])

In [5]:
print(y.shape)
y

(569,)


array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0,
       1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0,
       1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0,
       0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1,
       1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0,
       0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0,
       1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0,

# Using Sklearn's linear regression

In [6]:
from sklearn.model_selection import train_test_split
xtrain,xtest,ytrain,ytest = train_test_split(x,y,test_size=0.2,random_state=42)

In [7]:
print(xtrain.shape)
print(xtest.shape)
xtrain

(455, 30)
(114, 30)


array([[9.029e+00, 1.733e+01, 5.879e+01, ..., 1.750e-01, 4.228e-01,
        1.175e-01],
       [2.109e+01, 2.657e+01, 1.427e+02, ..., 2.903e-01, 4.098e-01,
        1.284e-01],
       [9.173e+00, 1.386e+01, 5.920e+01, ..., 5.087e-02, 3.282e-01,
        8.490e-02],
       ...,
       [1.429e+01, 1.682e+01, 9.030e+01, ..., 3.333e-02, 2.458e-01,
        6.120e-02],
       [1.398e+01, 1.962e+01, 9.112e+01, ..., 1.827e-01, 3.179e-01,
        1.055e-01],
       [1.218e+01, 2.052e+01, 7.722e+01, ..., 7.431e-02, 2.694e-01,
        6.878e-02]])

In [8]:
from sklearn.linear_model import LinearRegression
lr = LinearRegression()

In [9]:
lr.fit(xtrain,ytrain)

LinearRegression()

In [10]:
ypred = lr.predict(xtest)

In [11]:
from sklearn.metrics import r2_score

In [12]:
r2_score(ytest,ypred)

0.7271016126223568

In [13]:
lr.coef_

array([ 1.97130218e-01, -2.79472278e-03, -2.27758664e-02, -3.28622398e-04,
        4.11490191e-01,  5.00171192e+00, -1.00587030e+00, -4.91570446e+00,
        3.38393701e-01, -5.81425644e+00, -4.32261922e-01,  1.26325368e-02,
        8.24736376e-03,  1.24507529e-03, -1.80785086e+01,  2.20798677e+00,
        4.27375913e+00, -1.81589526e+01,  1.19449435e+00,  3.01203668e+00,
       -2.14438989e-01, -9.61718848e-03,  8.71176397e-03,  9.61253395e-04,
       -1.32384962e-01, -7.62670138e-01, -6.15742798e-01,  1.32619828e+00,
       -1.02113249e+00, -1.27363832e+00])

In [14]:
lr.intercept_

3.0563203369220395

# Making our OWN linear regression class

In [15]:
class MeraLR():
    def __init__(self):
        self.coef_ = None
        self.intercept_ = None

    def fit(self,xtrain,ytrain):
        xtrain = np.insert(xtrain,0,1,axis=1)
        betas = np.linalg.inv(np.dot(xtrain.T,xtrain)).dot(xtrain.T).dot(ytrain)
        self.intercept_ = betas[0]
        self.coef_ = betas[1:]

    def predict(self,ypred):
        ypred = np.dot(xtest,self.coef_) + self.intercept_
        return ypred

In [16]:
mlr = MeraLR()

In [17]:
mlr.fit(xtrain,ytrain)

In [18]:
ypred = mlr.predict(xtest)

In [19]:
r2_score(ytest,ypred)

0.7271016126214598

In [20]:
mlr.coef_

array([ 1.97130218e-01, -2.79472278e-03, -2.27758664e-02, -3.28622398e-04,
        4.11490191e-01,  5.00171192e+00, -1.00587030e+00, -4.91570446e+00,
        3.38393701e-01, -5.81425644e+00, -4.32261922e-01,  1.26325368e-02,
        8.24736376e-03,  1.24507529e-03, -1.80785086e+01,  2.20798677e+00,
        4.27375913e+00, -1.81589526e+01,  1.19449435e+00,  3.01203669e+00,
       -2.14438989e-01, -9.61718848e-03,  8.71176396e-03,  9.61253395e-04,
       -1.32384962e-01, -7.62670138e-01, -6.15742798e-01,  1.32619828e+00,
       -1.02113249e+00, -1.27363832e+00])

In [21]:
mlr.intercept_

3.0563203369680236